// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication.Components.Data;

#nullable disable

namespace MyApplication.Migrations
{
    [DbContext(typeof(AomDbContext))]
    [Migration("20251203211115_aaaaaaa")]
    partial class aaaaaaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.CallQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkillTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("CallQueue", "Aws");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.EmployeeRoutingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("WeekdayProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("WeekendProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WeekdayProfileId");

                    b.HasIndex("WeekendProfileId");

                    b.ToTable("EmployeeRoutingProfile", "Aws");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.Identifiers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwsUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Identifiers", "Aws");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.RoutingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoutingProfile", "Aws");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.RoutingProfileQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CallQueueId")
                        .HasColumnType("int");

                    b.Property<int?>("Delay")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RoutingProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CallQueueId");

                    b.HasIndex("RoutingProfileId");

                    b.ToTable("RoutingProfileQueue", "Aws");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses", "Aws");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcrRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("AcrRequestId1")
                        .HasColumnType("int");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsIntLoa")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLoa")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<int?>("SubOrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcrRequestId");

                    b.HasIndex("AcrRequestId1")
                        .IsUnique()
                        .HasFilter("[AcrRequestId1] IS NOT NULL");

                    b.HasIndex("EmployerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SiteId");

                    b.HasIndex("SubOrganizationId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("AcrOrganization", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrOvertimeSchedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcrRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("FridayTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOtAdjustment")
                        .HasColumnType("bit");

                    b.Property<int?>("MondayTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SaturdayTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SundayTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ThursdayTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TuesdayTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("WednesdayTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcrRequestId")
                        .IsUnique();

                    b.HasIndex("FridayTypeId");

                    b.HasIndex("MondayTypeId");

                    b.HasIndex("SaturdayTypeId");

                    b.HasIndex("SundayTypeId");

                    b.HasIndex("ThursdayTypeId");

                    b.HasIndex("TuesdayTypeId");

                    b.HasIndex("WednesdayTypeId");

                    b.ToTable("AcrOvertimeSchedules", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OvertimeTypes", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcrStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("AcrTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("varchar(32)");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManagerApprovedBy")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("ProcessedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime?>("RevertedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SubmitterComment")
                        .HasColumnType("varchar(128)");

                    b.Property<string>("WfmApprovedBy")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("WfmComment")
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AcrStatusId");

                    b.HasIndex("AcrTypeId");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("EmployeeId", "EffectiveDate");

                    b.ToTable("AcrRequest", "Employee", t =>
                        {
                            t.HasTrigger("tr_AcrRequest_AutoProcess");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcrRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("AcrRequestId1")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("FridayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("FridayStart")
                        .HasColumnType("time");

                    b.Property<bool?>("IsOtAdjustment")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSplitSchedule")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsStaticBreakSchedule")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("MondayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("MondayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("SaturdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("SaturdayStart")
                        .HasColumnType("time");

                    b.Property<int?>("ShiftNumber")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("SundayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("SundayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ThursdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ThursdayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("TuesdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("TuesdayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WednesdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WednesdayStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AcrRequestId");

                    b.HasIndex("AcrRequestId1");

                    b.ToTable("AcrSchedule", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcrStatus", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcrType", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.ActivitySubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AwsStatusId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("AwsStatusId");

                    b.ToTable("ActivitySubType", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityType", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.BreakSchedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("FridayTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("MondayTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("SaturdayTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("SundayTemplateID")
                        .HasColumnType("int");

                    b.Property<int?>("ThursdayTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("TuesdayTemplateId")
                        .HasColumnType("int");

                    b.Property<int?>("WednesdayTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("BreakSchedules", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.BreakTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Break1Time")
                        .HasColumnType("int");

                    b.Property<int?>("Break2Time")
                        .HasColumnType("int");

                    b.Property<int?>("Break3Time")
                        .HasColumnType("int");

                    b.Property<int?>("Break4Time")
                        .HasColumnType("int");

                    b.Property<int?>("Break5Time")
                        .HasColumnType("int");

                    b.Property<int?>("Break6Time")
                        .HasColumnType("int");

                    b.Property<int?>("Break7Time")
                        .HasColumnType("int");

                    b.Property<int?>("Break8Time")
                        .HasColumnType("int");

                    b.Property<int?>("BreakLength")
                        .HasColumnType("int");

                    b.Property<int?>("Breaks")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<int?>("LunchLength")
                        .HasColumnType("int");

                    b.Property<int?>("LunchTime")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiftLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BreakTemplates", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.DetailedSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivitySubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("AwsStatusId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsImpacting")
                        .HasColumnType("bit");

                    b.Property<int?>("Minutes")
                        .HasColumnType("int");

                    b.Property<int?>("OperaRequestId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<int?>("ScheduleRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivitySubTypeId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("AwsStatusId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OperaRequestId");

                    b.HasIndex("ScheduleRequestId");

                    b.ToTable("DetailedSchedule", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.EmployeeCurrentDetails", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("EmployerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubOrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable((string)null);

                    b.ToView("vw_EmployeeCurrentDetails", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.EmployeeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIntLoa")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLoa")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("OvertimeRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceAcrId")
                        .HasColumnType("int");

                    b.Property<int?>("SubOrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OvertimeRequestId");

                    b.HasIndex("ScheduleRequestId");

                    b.HasIndex("SiteId");

                    b.HasIndex("SubOrganizationId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("EmployeeId", "EffectiveDate");

                    b.ToTable("EmployeeHistory", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwsId")
                        .HasColumnType("int");

                    b.Property<string>("CorporateEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CorporateId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DomainLoginName")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NmciEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UsnAdminId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UsnOperatorId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AwsId");

                    b.ToTable("Employees", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Employer", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Manager", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("ActivitySubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ApproveBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApproveTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancelledTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OperaStatusId")
                        .HasColumnType("int");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RejectedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReviewedWfm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitterComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WfmComments")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("ActivitySubTypeId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("OperaStatusId");

                    b.HasIndex("StartTime");

                    b.HasIndex("EmployeeId", "StartTime");

                    b.ToTable("OperaRequest", "Employee", t =>
                        {
                            t.HasTrigger("tr_OperaRequest_ToDetailedSchedule");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperaStatus", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Organization", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SiteCode")
                        .HasColumnType("varchar(4)");

                    b.Property<string>("TimeZoneIana")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("TimeZoneWindows")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Site", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.SkillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkillType", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Skills", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("SkillDate")
                        .HasColumnType("date");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("Skills", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.SubOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwsStatusId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwsStatusId");

                    b.ToTable("SubOrganization", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Supervisor", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Security.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("AppRole", "Security");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "WFM"
                        },
                        new
                        {
                            Id = 5,
                            Name = "OST"
                        },
                        new
                        {
                            Id = 6,
                            Name = "ViewOnly"
                        });
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Security.AppRoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AppRoleId");

                    b.ToTable("AppRoleAssignment", "Security");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.EmailTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SendFromAddress")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.IntervalSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlOcmNiprFatalCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprFatalOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmNiprHoldCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprHoldOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmNiprReadyCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprReadyOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmSiprFatalCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprFatalOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmSiprHoldCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprHoldOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmSiprReadyCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprReadyOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlRdmUsnCount")
                        .HasColumnType("int");

                    b.Property<int>("BlRdmUsnEsdCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlRdmUsnEsdOldest")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("BlRdmUsnOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmAfuCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmAfuOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmCxSatCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmCxSatOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmEmailBuildoutsCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmEmailBuildoutsOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmUaAutoCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaAutoOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmUaSocManCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaSocManOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmUaUsnManCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaUsnManOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmValidationCount")
                        .HasColumnType("int");

                    b.Property<int>("BlSrmValidationFailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmValidationFailOldest")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("BlSrmValidationOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentCustomerCareCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentCustomerCareOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEmailOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentEssCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEssOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentNnpiASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNnpiCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNnpiCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprEmailOldest")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("CurrentSiprGdaOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentSiprGdaSpreadsheets")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprUaifCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprUaifOldest")
                        .HasColumnType("decimal");

                    b.Property<string>("CurrentUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVmCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentVmOldest")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("IntervalDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("IntervalEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("IntervalStart")
                        .HasColumnType("time");

                    b.Property<int>("MtdNnpiASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipCallsOffered")
                        .HasColumnType("int");

                    b.Property<string>("NaHpsmStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaImpactingEvents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaMajorCirImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaManagementNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaTodaysFocusArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Slr33EmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33EmMtdLos2")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntervalSummary", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("OiCategory", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedTimeToResolve")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("PostedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServicesAffected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersAffected")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OiEvent", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiEventUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OiEventUpdate", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiSeverity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OiSeverity", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OiStatus", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.ProactiveAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ProactiveTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsnInjectionAnnouncement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsnSiteAnnouncement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsnStatusAnnouncement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProactiveAnnouncement", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Service.Employee.Dtos.DailyScheduleRow", b =>
                {
                    b.Property<string>("ActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActivitySubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AwsStatusName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetailedScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsImpacting")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ScheduleDate")
                        .HasColumnType("date");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteTimeZoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubActivityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubOrganizationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_DailyScheduleDetails", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.CallQueue", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.SkillType", "SkillType")
                        .WithMany()
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.EmployeeRoutingProfile", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Aws.RoutingProfile", "WeekdayProfile")
                        .WithMany()
                        .HasForeignKey("WeekdayProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Aws.RoutingProfile", "WeekendProfile")
                        .WithMany()
                        .HasForeignKey("WeekendProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("WeekdayProfile");

                    b.Navigation("WeekendProfile");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.Identifiers", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.RoutingProfileQueue", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Aws.CallQueue", "CallQueue")
                        .WithMany()
                        .HasForeignKey("CallQueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Aws.RoutingProfile", "RoutingProfile")
                        .WithMany("RoutingProfileQueues")
                        .HasForeignKey("RoutingProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CallQueue");

                    b.Navigation("RoutingProfile");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrOrganization", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "AcrRequest")
                        .WithMany()
                        .HasForeignKey("AcrRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", null)
                        .WithOne("AcrOrganization")
                        .HasForeignKey("MyApplication.Components.Model.AOM.Employee.AcrOrganization", "AcrRequestId1");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.SubOrganization", "SubOrganization")
                        .WithMany()
                        .HasForeignKey("SubOrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AcrRequest");

                    b.Navigation("Employer");

                    b.Navigation("Manager");

                    b.Navigation("Organization");

                    b.Navigation("Site");

                    b.Navigation("SubOrganization");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrOvertimeSchedules", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "AcrRequest")
                        .WithOne("AcrOvertimeSchedule")
                        .HasForeignKey("MyApplication.Components.Model.AOM.Employee.AcrOvertimeSchedules", "AcrRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", "FridayType")
                        .WithMany()
                        .HasForeignKey("FridayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AcrOvertimeSchedules_FridayType_OvertimeTypes");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", "MondayType")
                        .WithMany()
                        .HasForeignKey("MondayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AcrOvertimeSchedules_MondayType_OvertimeTypes");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", "SaturdayType")
                        .WithMany()
                        .HasForeignKey("SaturdayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AcrOvertimeSchedules_SaturdayType_OvertimeTypes");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", "SundayType")
                        .WithMany()
                        .HasForeignKey("SundayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AcrOvertimeSchedules_SundayType_OvertimeTypes");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", "ThursdayType")
                        .WithMany()
                        .HasForeignKey("ThursdayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AcrOvertimeSchedules_ThursdayType_OvertimeTypes");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", "TuesdayType")
                        .WithMany()
                        .HasForeignKey("TuesdayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AcrOvertimeSchedules_TuesdayType_OvertimeTypes");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrOvertimeTypes", "WednesdayType")
                        .WithMany()
                        .HasForeignKey("WednesdayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_AcrOvertimeSchedules_WednesdayType_OvertimeTypes");

                    b.Navigation("AcrRequest");

                    b.Navigation("FridayType");

                    b.Navigation("MondayType");

                    b.Navigation("SaturdayType");

                    b.Navigation("SundayType");

                    b.Navigation("ThursdayType");

                    b.Navigation("TuesdayType");

                    b.Navigation("WednesdayType");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrRequest", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrStatus", "AcrStatus")
                        .WithMany()
                        .HasForeignKey("AcrStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrType", "AcrType")
                        .WithMany()
                        .HasForeignKey("AcrTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcrStatus");

                    b.Navigation("AcrType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrSchedule", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "AcrRequest")
                        .WithMany()
                        .HasForeignKey("AcrRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", null)
                        .WithMany("AcrSchedules")
                        .HasForeignKey("AcrRequestId1");

                    b.Navigation("AcrRequest");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.ActivitySubType", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.ActivityType", "ActivityType")
                        .WithMany("SubTypes")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Aws.Status", "AwsStatus")
                        .WithMany()
                        .HasForeignKey("AwsStatusId");

                    b.Navigation("ActivityType");

                    b.Navigation("AwsStatus");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.BreakSchedules", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.DetailedSchedule", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.ActivitySubType", "ActivitySubType")
                        .WithMany()
                        .HasForeignKey("ActivitySubTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Aws.Status", "AwsStatus")
                        .WithMany()
                        .HasForeignKey("AwsStatusId");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employees")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.OperaRequest", "OperaRequest")
                        .WithMany()
                        .HasForeignKey("OperaRequestId");

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "ScheduleRequest")
                        .WithMany()
                        .HasForeignKey("ScheduleRequestId");

                    b.Navigation("ActivitySubType");

                    b.Navigation("ActivityType");

                    b.Navigation("AwsStatus");

                    b.Navigation("Employees");

                    b.Navigation("OperaRequest");

                    b.Navigation("ScheduleRequest");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.EmployeeHistory", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "OvertimeRequest")
                        .WithMany()
                        .HasForeignKey("OvertimeRequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "ScheduleRequest")
                        .WithMany()
                        .HasForeignKey("ScheduleRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.SubOrganization", "SubOrganization")
                        .WithMany()
                        .HasForeignKey("SubOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("Employer");

                    b.Navigation("Manager");

                    b.Navigation("Organization");

                    b.Navigation("OvertimeRequest");

                    b.Navigation("ScheduleRequest");

                    b.Navigation("Site");

                    b.Navigation("SubOrganization");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Employees", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Aws.Identifiers", "Aws")
                        .WithMany()
                        .HasForeignKey("AwsId");

                    b.Navigation("Aws");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Manager", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaRequest", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.ActivitySubType", "ActivitySubType")
                        .WithMany()
                        .HasForeignKey("ActivitySubTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.ActivityType", "ActivityType")
                        .WithMany()
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employees")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.OperaStatus", "OperaStatus")
                        .WithMany()
                        .HasForeignKey("OperaStatusId");

                    b.Navigation("ActivitySubType");

                    b.Navigation("ActivityType");

                    b.Navigation("Employees");

                    b.Navigation("OperaStatus");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Skills", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.SkillType", "SkillType")
                        .WithMany()
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.SubOrganization", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Aws.Status", "AwsStatus")
                        .WithMany()
                        .HasForeignKey("AwsStatusId");

                    b.Navigation("AwsStatus");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Supervisor", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Security.AppRoleAssignment", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Security.AppRole", "AppRole")
                        .WithMany()
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppRole");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Aws.RoutingProfile", b =>
                {
                    b.Navigation("RoutingProfileQueues");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrRequest", b =>
                {
                    b.Navigation("AcrOrganization");

                    b.Navigation("AcrOvertimeSchedule");

                    b.Navigation("AcrSchedules");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.ActivityType", b =>
                {
                    b.Navigation("SubTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
