// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication.Components.Data;

#nullable disable

namespace MyApplication.Migrations
{
    [DbContext(typeof(AomDbContext))]
    [Migration("20251008203001_sitefix")]
    partial class sitefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcrRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsIntLoa")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsLoa")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<int?>("SubOrganizationId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcrRequestId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("SiteId");

                    b.HasIndex("SubOrganizationId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("AcrOrganization", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcrStatusId")
                        .HasColumnType("int");

                    b.Property<int>("AcrTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmitterComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WfmComment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AcrStatusId");

                    b.HasIndex("AcrTypeId");

                    b.HasIndex("EffectiveDate");

                    b.HasIndex("EmployeeId", "EffectiveDate");

                    b.ToTable("AcrRequest", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcrRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("BreakTime")
                        .HasColumnType("int");

                    b.Property<int?>("Breaks")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("FridayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("FridayStart")
                        .HasColumnType("time");

                    b.Property<bool?>("IsSplitSchedule")
                        .HasColumnType("bit");

                    b.Property<int?>("LunchTime")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("MondayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("MondayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("SaturdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("SaturdayStart")
                        .HasColumnType("time");

                    b.Property<int>("ShiftNumber")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("SundayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("SundayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ThursdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("ThursdayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("TuesdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("TuesdayStart")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WednesdayEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("WednesdayStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AcrRequestId");

                    b.ToTable("AcrSchedule", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcrStatus", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcrType", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.EmployeeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIntLoa")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoa")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<int>("SubOrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SiteId");

                    b.HasIndex("SubOrganizationId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("EmployeeId", "EffectiveDate");

                    b.ToTable("EmployeeHistory", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorporateEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CorporateId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DomainLoginName")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FlankspeedEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NmciEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UsnAdminId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UsnOperatorId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Employees", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Employer", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Manager", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OperaSubClassId")
                        .HasColumnType("int");

                    b.Property<int>("OperaSubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("OperaTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewedWfm")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmitTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitterComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WfmComments")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.HasIndex("OperaSubClassId");

                    b.HasIndex("OperaSubTypeId");

                    b.HasIndex("OperaTypeId");

                    b.HasIndex("StartTime");

                    b.HasIndex("EmployeeId", "StartTime");

                    b.ToTable("OperaRequest", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperaStatus", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaSubClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperaSubTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperaSubTypeId");

                    b.ToTable("OperaSubClass", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaSubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsImpacting")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperaTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperaTypeId");

                    b.ToTable("OperaSubType", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperaType", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Organization", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Schedule", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SiteCode")
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Site", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.SubOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("SubOrganization", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Supervisor", "Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.EmailTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SendFromAddress")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.IntervalSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlOcmNiprFatalCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprFatalOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmNiprHoldCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprHoldOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmNiprReadyCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprReadyOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmSiprFatalCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprFatalOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmSiprHoldCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprHoldOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlOcmSiprReadyCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprReadyOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlRdmUsnCount")
                        .HasColumnType("int");

                    b.Property<int>("BlRdmUsnEsdCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlRdmUsnEsdOldest")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("BlRdmUsnOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmAfuCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmAfuOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmCxSatCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmCxSatOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmEmailBuildoutsCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmEmailBuildoutsOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmUaAutoCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaAutoOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmUaSocManCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaSocManOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmUaUsnManCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaUsnManOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("BlSrmValidationCount")
                        .HasColumnType("int");

                    b.Property<int>("BlSrmValidationFailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmValidationFailOldest")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("BlSrmValidationOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentCustomerCareCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentCustomerCareOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEmailOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentEssCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEssOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentNnpiASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNnpiCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNnpiCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprEmailOldest")
                        .HasColumnType("decimal");

                    b.Property<decimal?>("CurrentSiprGdaOldest")
                        .HasColumnType("decimal");

                    b.Property<int>("CurrentSiprGdaSpreadsheets")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprUaifCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprUaifOldest")
                        .HasColumnType("decimal");

                    b.Property<string>("CurrentUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVmCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentVmOldest")
                        .HasColumnType("decimal");

                    b.Property<DateTime>("IntervalDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("IntervalEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("IntervalStart")
                        .HasColumnType("time");

                    b.Property<int>("MtdNnpiASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipCallsOffered")
                        .HasColumnType("int");

                    b.Property<string>("NaHpsmStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaImpactingEvents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaMajorCirImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaManagementNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaTodaysFocusArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Slr33EmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33EmMtdLos2")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntervalSummary", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("OiCategory", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedTimeToResolve")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("PostedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServicesAffected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersAffected")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OiEvent", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiEventUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OiEventUpdate", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiSeverity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OiSeverity", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.OiStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OiStatus", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Tools.ProactiveAnnouncement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ProactiveTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsnInjectionAnnouncement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsnSiteAnnouncement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsnStatusAnnouncement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProactiveAnnouncement", "Tools");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrOrganization", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "AcrRequest")
                        .WithMany()
                        .HasForeignKey("AcrRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.SubOrganization", "SubOrganization")
                        .WithMany()
                        .HasForeignKey("SubOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcrRequest");

                    b.Navigation("Employer");

                    b.Navigation("Manager");

                    b.Navigation("Organization");

                    b.Navigation("Site");

                    b.Navigation("SubOrganization");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrRequest", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrStatus", "AcrStatus")
                        .WithMany()
                        .HasForeignKey("AcrStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrType", "AcrType")
                        .WithMany()
                        .HasForeignKey("AcrTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcrStatus");

                    b.Navigation("AcrType");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.AcrSchedule", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.AcrRequest", "AcrRequest")
                        .WithMany()
                        .HasForeignKey("AcrRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcrRequest");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.EmployeeHistory", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Manager", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.SubOrganization", "SubOrganization")
                        .WithMany()
                        .HasForeignKey("SubOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Supervisor", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Employer");

                    b.Navigation("Manager");

                    b.Navigation("Organization");

                    b.Navigation("Schedule");

                    b.Navigation("Site");

                    b.Navigation("SubOrganization");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Manager", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaRequest", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", "Employees")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.OperaSubClass", "OperaSubClass")
                        .WithMany()
                        .HasForeignKey("OperaSubClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.OperaSubType", "OperaSubType")
                        .WithMany()
                        .HasForeignKey("OperaSubTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApplication.Components.Model.AOM.Employee.OperaType", "OperaType")
                        .WithMany()
                        .HasForeignKey("OperaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employees");

                    b.Navigation("OperaSubClass");

                    b.Navigation("OperaSubType");

                    b.Navigation("OperaType");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaSubClass", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.OperaSubType", "OperaSubType")
                        .WithMany("SubClasses")
                        .HasForeignKey("OperaSubTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OperaSubType");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaSubType", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.OperaType", "OperaType")
                        .WithMany("SubTypes")
                        .HasForeignKey("OperaTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OperaType");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.Supervisor", b =>
                {
                    b.HasOne("MyApplication.Components.Model.AOM.Employee.Employees", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaSubType", b =>
                {
                    b.Navigation("SubClasses");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee.OperaType", b =>
                {
                    b.Navigation("SubTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
