// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication.Components.Data;

#nullable disable

namespace MyApplication.Migrations
{
    [DbContext(typeof(AomDbContext))]
    [Migration("20250904152118_proactive")]
    partial class Proactive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntervalSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlOcmNiprFatalCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprFatalOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlOcmNiprHoldCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprHoldOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlOcmNiprReadyCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmNiprReadyOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlOcmSiprFatalCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprFatalOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlOcmSiprHoldCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprHoldOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlOcmSiprReadyCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlOcmSiprReadyOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlRdmUsnCount")
                        .HasColumnType("int");

                    b.Property<int>("BlRdmUsnEsdCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlRdmUsnEsdOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BlRdmUsnOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmAfuCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmAfuOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmCxSatCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmCxSatOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmEmailBuildoutsCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmEmailBuildoutsOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmUaAutoCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaAutoOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmUaSocManCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaSocManOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmUaUsnManCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaUsnManOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmValidationCount")
                        .HasColumnType("int");

                    b.Property<int>("BlSrmValidationFailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmValidationFailOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BlSrmValidationOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentCustomerCareCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentCustomerCareOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEmailOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentEssCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEssOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentNnpiASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNnpiCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNnpiCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprEmailOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentSiprGdaOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentSiprGdaSpreadsheets")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprUaifCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprUaifOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrentUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVipCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVmCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentVmOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IntervalDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("IntervalEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("IntervalStart")
                        .HasColumnType("time");

                    b.Property<int>("MtdNnpiASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdVipCallsOffered")
                        .HasColumnType("int");

                    b.Property<string>("NaHpsmStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaImpactingEvents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaMajorCirImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaManagementNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaTodaysFocusArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Slr33EmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33EmMtdLos2")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntervalSummary");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.EmailTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SendFromAddress")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorporateEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CorporateId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DomainLoginName")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FlankspeedEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NmciEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("UsnAdminId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UsnOperatorId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.OiCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("OiCategories");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.OiEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedTimeToResolve")
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("PostedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolutionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServicesAffected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeverityId")
                        .HasColumnType("int");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsersAffected")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OiEvents");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.OiEventUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OiEventUpdates");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.OiSeverity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OiSeverities");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.OiStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OiStatus");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Proactive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ProactiveTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsnInjectionAnnouncement")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UsnSiteAnnouncement")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("UsnStatusAnnouncement")
                        .IsRequired()
                        .HasColumnType("varchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Proactive");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SiteCode")
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.SubOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("SubOrganization");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
