// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApplication.Components.Data;

#nullable disable

namespace MyApplication.Migrations
{
    [DbContext(typeof(AomDbContext))]
    [Migration("20250827205208_Interval")]
    partial class Interval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApplication.Components.Model.AOM.EmailTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CcAddresses")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SendFromAddress")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ToAddresses")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorporateEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CorporateId")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("DomainLoginName")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FlankspeedEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NmciEmail")
                        .HasColumnType("varchar(64)");

                    b.Property<int?>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("UsnAdminId")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("UsnOperatorId")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.IntervalSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlRdmNnpiCount")
                        .HasColumnType("int");

                    b.Property<int>("BlRdmSiprCount")
                        .HasColumnType("int");

                    b.Property<int>("BlRdmUsnCount")
                        .HasColumnType("int");

                    b.Property<int>("BlRdmUsnEsdCount")
                        .HasColumnType("int");

                    b.Property<int>("BlSrmAfuCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmAfuOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmCxSatCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmCxSatOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmMsdCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmMsdOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmUaCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmUaOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BlSrmValidationCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("BlSrmValidationOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentCustomerCareCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentCustomerCareOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEmailOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CurrentEssCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentEssOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentNNPIAsa")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNNPICallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentNNPICallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprEmailCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprEmailOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentSiprGdaOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentSiprGdaSpreadsheets")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSiprUaifCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprUaifOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrentSiprVmCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentSiprVmOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrentUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("CurrentVmCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CurrentVmOldest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IntervalDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("IntervalEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("IntervalStart")
                        .HasColumnType("time");

                    b.Property<int>("MobilityQuotesInQueue")
                        .HasColumnType("int");

                    b.Property<decimal?>("MtdEmailMTTR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MtdNnpiASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdNnpiCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdSiprCallsOffered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnASA")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsAnswered")
                        .HasColumnType("int");

                    b.Property<int>("MtdUsnCallsOffered")
                        .HasColumnType("int");

                    b.Property<decimal?>("MtdVmMTTR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NaCurrentSvdPosture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaHpsmStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaImpactingEvents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaMajorCirImpact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaManagementNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NaTodaysFocusArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Slr33EmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33EmMtdLos2")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos1")
                        .HasColumnType("int");

                    b.Property<int>("Slr33VmMtdLos2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntervalSummary");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Organization");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SiteCode")
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Site");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.SubOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("SubOrganization");
                });

            modelBuilder.Entity("MyApplication.Components.Model.AOM.Supervisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Supervisor");
                });
#pragma warning restore 612, 618
        }
    }
}
